### ISSUE TITLE
Wrap certain elements in a container

### ISSUE THREAD

**Issue by joewhitsitt** [ITS-UofIowa/education.uiowa.edu#56]
As an indirect result of #49 (removing the sidebar), it appears some paragraph items (content blocks), etc. are expanding larger than they should be. I will audit and adjust these elements.

**Comment by joewhitsitt** [comment]
A spot check would be great to see if there are any elements, that look outside their bounds across browsers.

**Comment by UIJean** [comment]
I'm not sure if this is what you're looking for, but the overview and meet the faculty and latest new blocks on academic program pages are all having spacing issues. May need to revisit how these are built. Maybe use existing content blocks to share this info?

**Comment by joewhitsitt** [comment]
We might need to go over some of these in person. This issue was created to tackle noticeable out of bounds type issues. Unless you can provide specific details, I think overall I have fixed the main issue. With the sidebar gone there seems to be other issues related to the newly acquired space:

- Overview picture is chopping the main focus of the image.
  - Look into swapping out for center focus images
  - Adjust the image style/crop used.
  - Re-Style.
- Faculty profiles were aligned left max of three which left a lot of right space. (fixed by center aligning the three columns)
- Latest News (grey border) title position.
  - Some compromises were made to make sure these content block work on both full-width and contained layouts.

One issue I am trying to track down is if the menu dropdown that I implemented is out of left alignment with the page title and the page content. I think I found/corrected most instances of it.

**Comment by UIJean** [comment]
It looks like we may stop using overview and meet our faculty in their current state (on academic program pages). The /faculty pages look ok. 

Only other related issue I see is CALLOUT might have a margins or spacing issue.  Content doesn't stay within the margins of the page's content area. Sample on research& outreach page.

**Comment by joewhitsitt** [comment]
Regarding OVERVIEW - I understand with the new width but existing image and text length, these are no longer clipping appropriately. I haven't touched this, it is just responding to the new width. Instead of abandoning the field, I suggest you tweak the text to be longer and/or replace the images with ones that are more center focused.

Regarding MEET OUR FACULTY - Is something wrong with this that is turning you away? I just adjusted the spacing to deal with the larger width.

I believe I fixed the CALLOUT issue. Let me know if I didn't.

**Comment by UIJean** [comment]
Hi -


Thanks for fixing the CALLOUT.


Re: Faculty and Overview on academic program homepages:


We are working to create an Academic Program homepage structure that allows more control/flexibility on our end. These sections (overview, meet the faculty) MAY not be needed. Since those sections (overview and meet) simply don't show up if the fields aren't filled in, we can test our new layouts (that don't use those sections) without having to decide whether the fields need to be removed.


MEET OUR FACULTY - The most pressing issue is the restriction to a specific # of faculty. There is not a number (or even a fair range of numbers) that would satisfy all programs.


OVERVIEW - Since many programs will now have a large header image or video and there will be images associated with cards on the page, we are considering moving the text into the leading text box.


Hope that helps answer your questions.

- Jean

________________________________

**Comment by joewhitsitt** [comment]
This is now in STAGE set to be deployed.
